name: "Create Zip"
description: "create zip of unity packages"
inputs:
  projectName:
    required: true
    description: "name of the Unity project directory"
  packageName:
    required: true
    description: "name of the directory in Packages"
outputs:
  zipFile:
    description: "name of zip file"
    value: ${{ steps.set-zip-file.outputs.zipFile }}

runs:
  using: "composite"
  steps:
    - name: Get Version
      id: version
      uses: notiz-dev/github-action-json-property@7c8cf5cc36eb85d8d287a8086a39dac59628eb31
      with:
        path: "${{ inputs.projectName }}/Packages/${{ inputs.packageName }}/package.json"
        prop_path: "version"
    - name: Set Output
      id: set-zip-file
      run: echo "zipFile=${{ inputs.packageName }}-${{ steps.version.outputs.prop }}".zip >> $GITHUB_OUTPUT
      shell: bash
    - name: Create Zip
      uses: thedoctor0/zip-release@09336613be18a8208dfa66bd57efafd9e2685657
      with:
        type: "zip"
        directory: "${{ inputs.projectName }}/Packages/${{ inputs.packageName }}/"
        filename: "../../../${{ env.zipFile }}"
