name: Foo
on: push
jobs:
  bar1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: "Do bar"
        uses: ./.github/composite/bar
        with:
          hoge: "nyowa~"

