name: Foo
on: push
jobs:
  bar1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: "Yo"
        uses: ./.github/composite/create-zip
        with:
          id: "yo"
          projectName: "Unity"
          packageName: "net.shivaduke28.upm-ci-sandbox"
      - name: "Yo2"
        uses: ./.github/composite/create-zip
        with:
          id: "yo2"
          projectName: "Unity"
          packageName: "net.shivaduke28.upm-ci-sandbox2"
      - name: "check output"
        run: |
          echo ${{ steps.yo.outputs }}
          echo ${{ steps.yo2.outputs }}