name: push-main-branch
run-name: ${{ github.actor }} push to main branch
on:
  push:
    branches:
      - main
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "main branch pushed"
      # - uses: actions/checkout@v3
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: "14"
      # - run: npm install -g bats
      # - run: bats -v
