name: push-main-branch
run-name: ${{ github.actor }} push to main branch
on:
  push:
    branches:
      - main
jobs:
  show-properties:
    runs-on: ubuntu-latest
    steps:
      - name: Show github properties
        run: |
          echo "main branch pushed"
          echo ${{ github.workflow }}
          echo ${{ github.ref }}
          echo ${{ github.sha }}
          echo "main branch pushed"
